#!/usr/bin/env bash

shopt -s dotglob
shopt -s nullglob

directories=(~/repos/*/)

choice=$(printf '%s\n' "${directories[@]}" | sort | dmenu -i -l 10 -p "Project:")

if [ "$choice" ]; then
  alacritty -e ~/scripts/launch-nvim-in-dir "$choice"
else
  echo "Program terminated." && exit 0
fi
